### ISSUE TITLE
Progress reports

### ISSUE THREAD

**Issue by turikhay** [Minecraft-Malware-Prevention-Alliance/concoction#14]
Right before the scanning we _already_ know _exactly_ how many files we'll have to scan. It would be a nice touch. Future GUI applications will become more user-friendly.

**Comment by turikhay** [comment]
Ah sorry I never noticed #13

**Comment by Col-E** [comment]
If this is in reference to any tools utilizing concoction, those issues should be directed to those projects. We'll offer a generalized scanner and an API to use in your own projects. How those projects utilize concoction is up to them.
